### PR TITLE
bluez: fix panic caused by unsafe type assertion

### PR DESCRIPTION
**Pull request by ddelazerda**

### CODE REVIEW

**Comment by darkhz** [comment]
@ddelazerda did you experience a panic before, with the current code?

**Comment by ddelazerda** [comment]
Yes, as soon as I launched bluetuith it would panic. With my changes it doesn't panic and works just fine.

**Comment by darkhz** [comment]
This pull-request will not be merged, because types must be asserted properly across the all property accessors. See #42, and if possible, test it and post your review here.

**Comment by ddelazerda** [comment]
I tested your test branch and it does solve the issue. I don't know how dbus works so when I set to fix the issue I was just trying to make it not panic :)

**Pull request closed without merging**
